name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  check-code:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup
        run: make setup
      - name: Static Code Analysis
        run: make check-code
      - name: Run Unit Tests
        run: make test